defaults: &defaults
  TIMEZONE: 'Paris'

  # Configuration variables for Redis.
  REDIS_URL: redis://localhost:6379
  #  REDIS_URL: redis://18.206.91.150:6379   #

  REDIS_PASSWORD: ~ # By default no password is sent to Redis server. Change this if you want to connect using password.

  # site host
  URL_HOST: localhost:3000
  URL_SCHEME: http

  # admin role account
  ADMIN: 'rittu@mailinator.com'

  #  database.yml variables
  #  RDS_HOSTNAME: dietbitcoinico-org.c0vfzk4vecgn.us-east-1.rds.amazonaws.com
  RDS_HOSTNAME: cccubes-stage.cnccjqejwukh.ap-southeast-1.rds.amazonaws.com

  # session expire time (seconds)
  SESSION_EXPIRE: '60'

  # Configuration variables for mailer (production only).
  #
  # The variables below are the minimal set of configuration required for mailer to work.
  #
  # More variables are available at:
  # – https://github.com/mikel/mail
  # – http://api.rubyonrails.org/v4.2/classes/ActionMailer/Base.html
  # – config/environments/production.rb at config.action_mailer.smtp_settings
  #
  SMTP_ADDRESS: smtp.sendgrid.net
  SMTP_PORT:    587
  SMTP_USERNAME: apikey
  SMTP_PASSWORD: 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
  SMTP_AUTHENTICATION_TYPE: :plain # Can be plain, login or cram_md5.

  S3_ACCESS_KEY: 'AKIAI2HHYZAEQOOSNSVQ'
  S3_SECRET_KEY: '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'
  S3_BUCKET_NAME: 'cccubes-kyc'


  # email accounts
  SUPPORT_MAIL: support@cccubes-stage.com
  SYSTEM_MAIL_FROM: do-not-reply@cccubes-stage.com
  SYSTEM_MAIL_TO: do-not-reply@cccubes-stage.com
  OPERATE_MAIL_TO: operate@cccubes-stage.com

  # WebSocket Streaming API settings
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080

  # Uncomment following lines to enable secure WebSocket (wss)
  # WEBSOCKET_SSL_KEY: 'your_server.key'
  # WEBSOCKET_SSL_CERT: 'your_server.crt'

  RABBITMQ_HOST: 34.194.253.116
  RABBITMQ_PORT: 5672
  RABBITMQ_USER: rbmq
  RABBITMQ_PASSWORD: FaMt3ydE5vpLHLdw

  # pusher settings
  PUSHER_APP: '571926'
  PUSHER_KEY: f6fe7174fb47201da259
  PUSHER_SECRET: c7491005c74c028686c8
  PUSHER_HOST: api.pusherapp.com
  PUSHER_CLUSTER: ap2
  PUSHER_PORT: '80'
  PUSHER_WS_PORT: '80'
  PUSHER_WSS_PORT: '443'
  PUSHER_ENCRYPTED: 'on'

  TWILLIO_REGION: 'HK'
  TWILIO_NUMBER: 85264507707
  TWILIO_SID: AC8f11100cadb66b3feb185eaeab481527
  TWILIO_TOKEN: 6ef4cb87c95355515733fd5c1286f6b1

  RECAPTCA_SITE_KEY: 6Ldue1QUAAAAAIOWR9DdZlu28-S5MhtfpbZ9SRoH
  RECAPTCA_SECRET_KEY: 6Ldue1QUAAAAANE_6bgsc6Mvqerlgsn3gGAkA4sl

  # Configuration variables for sign in with Google.
  # See https://github.com/zquestz/omniauth-google-oauth2
  GOOGLE_OAUTH2_SIGN_IN:      ~ # Set to "on" to enable.
  GOOGLE_CLIENT_ID:
  GOOGLE_CLIENT_SECRET:
  GOOGLE_OAUTH2_REDIRECT_URL: ~ # Specify URL address to which user will be redirected after successful sign in.

  # Configuration variables for sign in with Auth0.
  # See https://github.com/auth0/omniauth-auth0
  AUTH0_OAUTH2_SIGN_IN:       ~ # Set to "on" to enable.
  AUTH0_OAUTH2_DOMAIN:
  AUTH0_OAUTH2_CLIENT_ID:
  AUTH0_OAUTH2_CLIENT_SECRET:
  AUTH0_OAUTH2_REDIRECT_URL:  ~ # Specify URL address to which user will be redirected after successful sign in.

  # Configuration variables for API CORS.
  #
  # Set list of allowed origins using the variable below.
  # By default it allows access to API from all origins.
  # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
  API_CORS_ORIGINS: '*'

  # Configuration variables for Sentry.
  SENTRY_ENV:          production # Specify environments separated by comma for which Sentry should be initialized.
  SENTRY_DSN_BACKEND:  ~          # Specify Sentry DSN used for Rails application.
  SENTRY_DSN_FRONTEND: ~          # Specify Sentry DSN used for JavaScript application.

  # Configuration variables for appearance.
  LOGO_URL:                       ~
  HEADER_BACKGROUND_COLOR:        ~
  HEADER_BORDER_COLOR:            ~
  HEADER_LINK_COLOR:              ~
  HEADER_LINK_HOVER_COLOR:        ~
  HEADER_RUBRIC_ACTIVE_COLOR:     ~
  HEADER_RUBRIC_BACKGROUND_COLOR: ~
  MAIL_HEADER_BACKGROUND_COLOR:   ~

  # Configuration variables for webhooks.
  WEBHOOKS_SECURE_URL_COMPONENT: ~ # Optional. Set value if you want to secure URL to webhooks.
  # Example:
  #   When WEBHOOKS_SECURE_URL_COMPONENT is set to "B6p2csgf2h" the URL to webhooks becomes /webhooks/B6p2csgf2h/btc/hook.
  #   The default URL is /webhooks/btc/hook.

development:
  <<: *defaults
  # Development configuration variables for sign in with Google.
  GOOGLE_OAUTH2_SIGN_IN:      on
  GOOGLE_CLIENT_ID:           1044454023387-emhp5vmfnp5cf1n9juk09g8gcckrova7.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET:       tAFZvO200-0z3MpCyOpkPH0G

  # Development configuration variables for sign in with Auth0.
  AUTH0_OAUTH2_SIGN_IN:       on
  AUTH0_OAUTH2_DOMAIN:        peatio-playground.auth0.com
  AUTH0_OAUTH2_CLIENT_ID:     lGKS9ADpknQr415RNZrrQTf3Jh8k2Fvc
  AUTH0_OAUTH2_CLIENT_SECRET: LxUPnrrrpRHSB-vVgWU3TwmakQ8acY5mYVTaVgkREQL3i9avjpOnWTXSSEsrbLzK

  SECRET_KEY_BASE: ec7ffa7f1e53b586f2ad072518776a153b14f40ea77e5aa17b9b3ab5145ac29f018c2da13c626102b2d7c749b60f8fc81798579a7e820b96821d431b5fc144c3
  JWT_SHARED_SECRET_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBOWt6akVBb2NJSWZva3hhSTZHMXMwRzczWnlyWXVOcWtnaVR2ek9haGRoSE9FUWFJCmpEY3EvRzVuSW5Ic25qdkZMM3oyY2tkTFBURWh3VE5HNlEybkZ2TkRTQlJHSVRJSFVGaW1KM2NBTTlzYzl2NzYKaE9vUDh5NUd4RHllMjcwWjE4UWFjOEdkMGZyZGZ6Z1lvQ3BTWk1yK3c5ZFRIU0dpcXczaW9YUjJ5akNSZm5XTgp1NXM4dGJaL0s4aFpUYUx5cUs1Znd6UTJrR3F4dVl1YnRuRlpOYUhmN2ZNL09IOXZETG1MNi9yczhPWURiaUhQCjFvVkFJUVliZEZpNU4zZlJhcnJQdGRrMGlsZ2VNb0Z3YmlidDg1Z2xHYUJldE5JVnN0QkVzdXRvaW5CUWlmYzgKNUpGdmpXYVZNcmdrc2RaVnVNWVoxS0dYN2k4KzNDNzRNYzRXdHdJREFRQUJBb0lCQUZZMGp2eWNMVUFOa1k5NQp3YTFvTHorOHR3YjY3aU8xRXdNaUhuUmUvSUF3dHlrcVdqeUpTcGhUby9GZ1ltcjNqSXFVZUVXRFFvaEdYQVFkCkNHS2xqcWZ2dU1yUG5jUWNtSWE4b0ZzTHdaeGt3bnlJdmZJcllpM0JNcStZY0JtRTFEaTZ3RzluZ3U5dG1IemcKaTIzem9pYjVEYlpKOVNNckZKNCtHK1phdHdFSTB2VHBWbENVeDQ5UHRIdzJkWWJhR04xMS8rZnQ1MEJYdytYQgp0ZVpFTjVOYTR0SEhWcHB3aUdFd1BtblhyN292Vmo0eVFzdnhHaEVOTUlrMkNJVkxpQmlhUWhoNTFZYUdnc1AyCmRpeVZRdXF1L2Uyd3cyYzh1c2tlKzN4aW5QdThiY3pJQVZoY3l2RFJlMzFmN0VBOWdYRHU5SDFzQUxrajdXNjYKdjkrRjJhRUNnWUVBLy9Vd3Q1L1lBT3Q1alhIbkRjZ3drbzNSTDlwZUpSUzF3K1BSbEhWV3NmdExZTWx3SERORApwbVRNYmtJUE9yelpqMmJlODcwZm02N3pscGczVXdJbHlmTkhwb0xQL0hRVUp5eS82TWtNbDNhUTQ4MktHM3ovCmdKMDZwQkdGMzZ0Uk1iQ25zN09vOEhZRzNMK0FWRVZ0cnpWc3VnNHBRc21lZ1lCVmNtcnBsRGtDZ1lFQTlsZEoKN3lkUURpL2xjckt1b1JBdEhjdEhwS3Z5VUVVQ1JNMlB3WkY3R3ExVXFoUzFDdGxubDBNNnBDdGIrY25QbWU5SQpZbUZjZCtRZWE3TVpHVXduZmZldUpjeGg0TlI4SjZlZFRTRThpZ3owbG4wdmZ0WnBmcUdLUEtsZE4wakdDdHVvCkZRR0U0cXQ0SXVPNC9Yemlhazd2VlZNbmNJU2JCZlk0VURRUlltOENnWUJ5a0xiTG1mbysveWNiRG42VEJxWG4KRXg4c3doc2RrZFdCNXJqcU1GTXJ1d1VVUDFXMDZhVkFGeUlCd0FPOUVNWjRqMXovMEFrVDBBMHJ2Tm9XaDRHTwprUnZqQmU0K1cxNmg0ai9MM0NHTXNmOU1WN1dYZEMyUXpjOXZuSUJGaXhMK29NbVBmNzBBVkhQaDNyMTcrcytMCmV1ZzlweFVFMWVYaXBTU1o0QXpJMFFLQmdHTEJVWmwzZUNlSDJnTW1VTTJ1NzNkUFJCUm0va2hoc2V3bFFHbEkKU2tMQ2svdHZPN2p5dVEyeDNQTnRrbnpNQTliaFQzSnBONm0wb09GcU5qaW5CL24rN2lpbkMrSVhMUUswdG1IeQpYaE8xNStQZ29jYkdiQnBnNWtzMVZuSlFVVnlPL0k0WFFzK2dFQlJrbUllK3BnSWFUT1kyNU11OXpXd1JiamZ3Cjk3c3ZBb0dBSTYvOEtRdE1ZMWkyenNjUVczL0h2eUxBM0s4N1dUMjdTU3RwUTRCeWhQTmJtYmZvbUpmbXQrZmkKN2NyTXlEdFlUNTVOeW5UOW5QTUJZTXMyT2J5WWdwNjIvZ3daOG03V3luQitRMm1ENUtaYmc5eGwvNzVUeDlzVgpVbVNPRFdib0lUOFlwTDh6WS9mN29VVk0zRnVvZUJqQ1hybkE4S1c4Q082Q2dicjRETGM9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

test:
  <<: *defaults

stage:
  <<: *defaults
  RDS_DB_NAME: 'cccubes-stage01'
  RDS_USERNAME: 'cccubes-stage01'
  RDS_PASSWORD: 'GbKAtOZ0mF6Zf7YF'
  POOL: 50
  # site host

  URL_HOST: cccubes-stage.com
  URL_SCHEME: https

  SECRET_KEY_BASE: 49c48bfb05e83d24763173bd7488f238ffe4a2339f36537ebaf56024b077cde3fabf4f0106fef52021ec52b3ebd7e87ae0178bc87bada70723b857dd999924fc
  JWT_SHARED_SECRET_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdU4wbkhOaFUycm5lNXhNUkxCbVh2bDRBcWtBcU1LT0JBVGk4NDRpeU1HdU5uT0EyCmRQRHRmcTJYeENYY0FvQW4yc0dhdFRuWnhnSlpkd1Y3Q050VzdKRzg4bVExWGFBTFdlVEd6VGkwTVZsMHNHUVYKT1MycWY3a21mWlFKaDhDRU1ZNS9oQ1JKQzBxZzZMN09LcmpuT2FaZ3BGWXVoNUdxQ05ONkI1V2Nmd3g5TksrWApWK3h5eHJEb2l4eG15ZEhBMkViT1MrWXh2S1JlVXJXS3k1TElSVWlpQzA0TVB2WXRrcW5CY3dyek5mY21UTU1MCnB0MjhiWVl5elQ0S09jcDFvVTFnUnNqa0kwWmJNYUdFRlNjWk1EU2l5NGsrSnZ6dmJubXphcExDSTFPcHJWMmYKZW1TRzYydi9DaWVaOU5Hbm82YUh3bGNXR0lVTmN6TXgvVUp5dlFJREFRQUJBb0lCQVFDMDlRYU1YZGJ5SkcvbAprZXlGVnFnTFdNa2QzcUZ0Nng4a3F2MTdYUnZQK2ZndFQreittN2hmQUY1SFN5Z0o2cGtZc2R0VytzSUo2ZExaCmh5dmdoNVNYRGpIK3M4anBWUGpIamdKc2NNMHlZWGF3RThnU3FIajFmYkFIelJsbklUUkZyazkwY25CdDlTZDkKclFqekdQeCttamFQcHl6MDE4bXh5aER4eTZuZFVoaTRNMVNVRUVmWGdRMitoWHM4WS82RzVoZzZwMnFJWnhCUgp4d2oxeEIvMHZnUENQVmRMdUIzZ0poR1ZoellDVUV0QkdNTEViZDhnQU0xWGNDSnRvaUpHdldGY2xBT056L3pqCjYvYStHQmxNZVNOdEJVMHNtVHVLL1NvTFMxSVhpc2h3cjVJMmpta1BiaSt3M0ttSVVNZW1QMEQxS0w0QVc5ZHUKSDVvWmpCTUJBb0dCQU80cU9IZHhycVlsaGVZRE9CNkNKVUlnbDZIYTZ2d01PbU5vREdUL1JMUnBBeFRlcWJxUwo2VnJHdHNGSU9WWTZLTzBpMm9SczNNdW9OZ0o4SGVWQ1dhNS9zbVhYeE0rQTZRR1A1ZEhuM3YrV25vVDU2RVRPCkh3a2I1d2FhbHpaMS8wUm9GbGR5a2QwN0hweGdxVjJTRER1SUUycGhaeGxJTlQveklSOFJjYWlwQW9HQkFNYTEKSGFkcmdXWXZpOWpPd0NNYzNkYVBzbDZYV3dhQmd0QjBRYXVqRWhHMzBvYlNDV0tHR0RiSU92TnFSK2o5TDJEWApCR0h6U2dBeTJHdDRzSS9ialhJMW40c0NyUDJzYUJrSWx1aWhuak95R0MwTjFieGxjNGNibU1DaXNWVVRScXNUCk1IblcrZmFKN3JPb1U1TmIvbmlQNFBzamFhdC9tWnkraEtZZWRHSDFBb0dBY0pnSFAvaS9yNDZYd2NrTjArYUYKUk1EeHpyUVhXWGRTZDBKdWNhVDR6eTNDSmpDcUh5bHJKdDVBOGhsNStkamZGbFRlNTdJcnBDQnZBRGU3VG5KUwp3WnRmTktTUVIrVlN3c2xMeGpPUGlsZWpzNHdPRWRFOGZPcnpDbjAxTmFzTk5rTGJKUlpsL1NnQTdiOEk4dEtqCjg5VCtFTkhoa3VNL1FXOW8zaTQ2QkprQ2dZRUF4UmRvTG1Obm1kK1hLcGtINHN3RERZckNOU2lUVk1TbzUvSW8KSVFKQ0xlalNuSDlBWjhUeHg0U2JWRTBhdm5KQ3lCNzliZHBPa0J2ZXBkcXo1anl5ODVGVWlpRkJUT3Z3NU1PcwpTMW5pL1F1dEJ5TXQyUXdYcHU4c2VBWG5OcWREOVBPM3BXSWgxUFBERzlmZDdjL1ZlK2ZhRTc5d1ZIYmYrcVRPCkZhY25jUEVDZ1lFQTNLTjNxZ3E5Y3ZqM3E5cTJUekt6MFpLYVVkbm1yY0txbVBzdU1VeXpoUlpHa0RyYmlnZG0KMU1jSU90VVlOZy81aWVUYWc4bEpXcW9yL1RCRjhaNmRTV0VDd3hURy9LakU5Vk1BcS94QVU3YUZ0TUFOT1h0TApaVFVkNUl3Z2N1STcweCtYQVRGZ1JldGFrcDVHSCtRYmhoYTNOUnl2UEJGcUd2NS8yNnlHV1VZPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

  RECAPTCA_SITE_KEY: 6LerqowUAAAAAKP15BiSCquxGyiWVhhf8foD7zSA         # cccubes-stage.com
  RECAPTCA_SECRET_KEY: 6LerqowUAAAAAE4kIOLoGV8AZwkR98lC1uFib2nO

  REDIS_URL: redis://cccubes-stage-001.ja656n.0001.apse1.cache.amazonaws.com:6379
  RDS_HOSTNAME: cccubes-stage.cnccjqejwukh.ap-southeast-1.rds.amazonaws.com

  # admin role account
  ADMIN: 'dev.cccubes@gmail.com'   #shubham@123

  # Stage configuration variables for sign in with Google.
  GOOGLE_OAUTH2_SIGN_IN:      on
  GOOGLE_CLIENT_ID:           131450012324-6e3ndk6on1t6k8sbbvd9fjltm1cvasbr.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET:       0IRJ3CwSKQbigbRy3LlX7Kg9

  # Stage configuration variables for sign in with facebook.
  OMNIAUTH_FACEBOOK_SIGN_IN:        on
  FACEBOOK_CLIENT_ID	:       546572719076462
  FACEBOOK_CLIENT_SECRET:   a05a4cb8ac92b8fd5716c1c7145f66f9

  RABBITMQ_HOST: 172.31.7.62
  RABBITMQ_USER: mqcccubes
  RABBITMQ_PASSWORD: VwSMxP6N2eTnJu4Knj

  PUSHER_APP: '698830'
  # PUSHER_KEY: 03b528c18ecd8264e665
  # PUSHER_SECRET: 502933256120799b4c22
  PUSHER_KEY: 0413d4aeb1eda1108086
  PUSHER_SECRET: 9e3d99d995c1d9125de5

  S3_ACCESS_KEY: 'AKIAI2HHYZAEQOOSNSVQ'
  S3_SECRET_KEY: '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'
  S3_BUCKET_NAME: 'cccubes-kyc'

  # email accounts
  SUPPORT_MAIL: support@cccubes-stage.com
  SYSTEM_MAIL_FROM: do-not-reply@cccubes-stage.com
  SYSTEM_MAIL_TO: do-not-reply@cccubes-stage.com
  OPERATE_MAIL_TO: operate@cccubes-stage.com

production:
  <<: *defaults
